# Generated by Django 2.0 on 2018-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('company', models.TextField(blank=True, max_length=50)),
                ('visit_area', models.TextField(blank=True, max_length=50)),
                ('purpose', models.TextField(blank=True, max_length=50)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
