# Generated by Django 2.1 on 2018-10-15 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('org_url', models.URLField()),
                ('FAX', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visit_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('company', models.TextField(max_length=200)),
                ('purpose', models.TextField(max_length=200)),
                ('visit_area', models.TextField(max_length=200)),
                ('host', models.TextField(default='', max_length=200)),
                ('signature', models.URLField()),
                ('key', models.TextField(default=0, max_length=200)),
                ('is_out', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(default=datetime.datetime(2018, 10, 15, 7, 52, 13, 721440, tzinfo=utc))),
                ('logout_time', models.DateTimeField(default=datetime.datetime(2018, 10, 15, 7, 52, 13, 752557, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(default='0912345678', max_length=10)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('personal_ID', models.CharField(blank=True, max_length=10)),
                ('org_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Organizations')),
            ],
        ),
    ]
