# Generated by Django 2.0 on 2018-08-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(verbose_name='Enter time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(verbose_name='Exit time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_area',
            field=models.TextField(max_length=200),
        ),
    ]
