# Generated by Django 2.0 on 2018-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180824_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='signature',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enter time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Exit time'),
        ),
    ]
