# Generated by Django 2.0 on 2018-08-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20180827_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='signature',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
