# Generated by Django 2.0 on 2018-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180827_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='signature',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
