# Generated by Django 2.0 on 2018-09-05 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180827_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='key',
            field=models.TextField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 2, 4, 57, 52431, tzinfo=utc), verbose_name='Enter time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='signature',
            field=models.URLField(),
        ),
    ]
