# Generated by Django 2.1 on 2018-09-14 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180827_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 3, 13, 13, 398261, tzinfo=utc), verbose_name='Enter time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='signature',
            field=models.URLField(),
        ),
    ]
