# Generated by Django 2.1 on 2018-09-14 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20180905_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 4, 14, 40, 242409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 4, 14, 40, 280015, tzinfo=utc)),
        ),
    ]
