# Generated by Django 2.0 on 2018-09-04 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20180828_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 8, 6, 25, 760739, tzinfo=utc), verbose_name='Enter time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='signature',
            field=models.URLField(),
        ),
    ]
