# Generated by Django 2.1 on 2018-09-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20180914_1214'),
        ('trips', '0005_auto_20180914_1113'),
    ]

    operations = [
    ]
