# Generated by Django 2.0 on 2018-09-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20180914_1214'),
        ('trips', '0005_auto_20180914_1113'),
        ('trips', '0007_auto_20180904_1606'),
    ]

    operations = [
    ]
