# Generated by Django 2.1 on 2018-09-18 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_merge_20180918_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 5, 18, 35, 512389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 5, 18, 35, 543593, tzinfo=utc)),
        ),
    ]
