# Generated by Django 2.1 on 2018-09-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20180918_1318'),
        ('trips', '0008_merge_20180918_1343'),
    ]

    operations = [
    ]
