# Generated by Django 2.0 on 2018-09-26 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_merge_20180918_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.TextField(max_length=200)),
                ('org_url', models.URLField()),
                ('FAX', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='visit_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('company', models.TextField(max_length=200)),
                ('purpose', models.TextField(max_length=200)),
                ('visit_area', models.TextField(max_length=200)),
                ('signature', models.URLField()),
                ('key', models.TextField(default=0, max_length=200)),
                ('is_out', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 8, 19, 49, 792149, tzinfo=utc))),
                ('logout_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 8, 19, 49, 909834, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_out',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='key',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_area',
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='personal_ID',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='org_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Organization'),
        ),
    ]
