# Generated by Django 2.0 on 2018-09-27 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20180926_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='FAX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit_log',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 17, 13, 139662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit_log',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 17, 15, 662007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
