# Generated by Django 2.0 on 2018-09-27 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20180927_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit_log',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 19, 59, 219494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit_log',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 19, 59, 422572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='personal_ID',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
