# Generated by Django 2.1 on 2018-09-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_merge_20180919_1659'),
        ('trips', '0012_auto_20180927_1119'),
    ]

    operations = [
    ]
